### ISSUE TITLE
Default static is index.tpl.html

### ISSUE THREAD

**Issue by smacpherson64** [40Digits/gulp-eta#11]
Would it be a good idea to switch the default `index.tpl.html` to `sample.tpl.html`? For me I have accidentally overwritten a few index.html files.

**Comment by besimhu** [comment]
That's fine. 

However, the static area doesn't get generated with `gulp init`. Additionally, it's there as a default once `localhost:3000` is loaded without a proxy. 

What looks and sounds like to me is that you are making edits in the root `index.html` vs in the `_src/static/` index file. Thus the rewrites.

**Comment by smacpherson64** [comment]
Hey Besim, you are absolutely right! It was my fault that those were overwritten. I made this suggestion because changing the name could prevent frustration for people who are new to ETA and using it for static sites.

**Comment by ghost** [comment]
gulp-eta will be deprecated, hence we will be closing the current existing issues.
