### ISSUE TITLE
Unable to overwrite ETA default tasks

### ISSUE THREAD

**Issue by smacpherson64** [40Digits/gulp-eta#13]
When working with Chad on trying to overwrite a default ETA task he discovered that the tasks were not functioning properly:

> ...[T]he problem is that the tasks are setup ​_before_​ the merge. ​[4:36]  so the tasks that other tasks depend on are only ever using eta’s config and never gets the custom ones.
#### Example - Setup that is not overwriting the default ETA `production` task:

```
var gulp = require('gulp');
var eta = require('gulp-eta');
var cssBase64 = require('gulp-css-base64');

var options = {
    production: {
        tasks: ['minifyCss', 'tumblr', 'uglifyJs']
    }
}

gulp.task('tumblr', function () {
    console.log('Base64 encode of fonts complete');
    return gulp.src('style.css')
    .pipe(cssBase64({
        extensionsAllowed: ['.svg', '.eot', '.eot?#iefix', '.ttf', '.woff']
    }))
    .pipe(gulp.dest(''));
});

eta(gulp, options);

```

**Comment by ghost** [comment]
gulp-eta will be deprecated, hence we will be closing the current existing issues.
