### ISSUE TITLE
Readme describes a 'minifyJs' task, the correct name is 'uglifyJs'

### ISSUE THREAD

**Issue by prichey** [40Digits/gulp-eta#16]
Compare https://github.com/40Digits/gulp-eta#minifyjs to https://github.com/40Digits/gulp-eta#production.

**Comment by chadwatson** [comment]
Fixed: [d1f29e0](https://github.com/40Digits/gulp-eta/commit/d1f29e0439db7ccbdacf65cf2c27904154eab87f)
