### ISSUE TITLE
Still several places assuming root as 'assets' even when overridden in Gulpfile.

### ISSUE THREAD

**Issue by prichey** [40Digits/gulp-eta#7]
I'm giving this a spin this weekend and I'm noticing that several paths are 404-ing when using a custom assets path. Just wanted to jot these down while they're on my mind.
1. `_footer.html` assumes 'assets/js/main.js`.
2. `_utilities.scss` assumes `assets/images/backgroundsize.min.htc` for `%bg-cover` `-ms-behavior`.
3. `_fonts.scss` assumes `assets/fonts/font-folder-name/` for the commented-out font face. 

Not sure if it's worth templating out the last two Sass files, but I think at least the footer partial would be pretty easy to pull in the correct path for.

**Comment by besimhu** [comment]
1) is this for the static generator? 
2) I think we should just remove this. It's used for IE8 background size cover support. Hardly do IE8 today. 
3) I believe this is just an example of how to organize fonts & call in.

**Comment by ghost** [comment]
gulp-eta will be deprecated, hence we will be closing the current existing issues.
