### ISSUE TITLE
Missing slash in symbols template file.

### ISSUE THREAD

**Issue by prichey** [40Digits/gulp-eta#8]
The symbols font-face is missing a slash between `fontPath` and `fontName` in `symbols.tpl.scss` which leads to a 404-ing `/fonts/symbolssymbols.woff` file (etc.). I can do a PR for this, just wanted to open an issue for it.

**Comment by chadwatson** [comment]
I ran into this yesterday, too. Just published an update for it.

**Comment by prichey** [comment]
![giphy 3](https://cloud.githubusercontent.com/assets/1418487/11171540/46344740-8bb8-11e5-9e6f-66e40c2c0971.gif)
